### ISSUE TITLE
Effects persist after bingo game ends

### ISSUE THREAD

**Issue by scarlettcloud** [Steaf23/BingoReloaded#1]
### **Overview**
If effects are applied in the admin menu to players for a Bingo game, those effects persist after the game ends.

### **Tested on:**
1.19.2 Purpur (Spigot), hooked into Velocity network

### **Steps to Recretate:**
1. Open BR admin menu, select any game type or card, and apply player effects
2. Start the game, and then end the game
3. Test if effects are still applied

### **Relevant Logs**
N/A - no errors thrown

**Comment by Steaf23** [comment]
fixed in v1.3.1
