### ISSUE TITLE
On bingo end command + Placeholders

### ISSUE THREAD

**Issue by Menacho15** [Steaf23/BingoReloaded#10]
If it's possible, add a way to send commands to the console when a game ends and add placeholders for player stats using PlaceholderAPI. Thank you :).

**Comment by Steaf23** [comment]
thanks for trying out my plugin, sending commands after the game is over is already implemented for the next version. As for placeholders, I will look and see what i can do with them 👍

**Comment by Steaf23** [comment]
Placeholder API support is implemented as of V2.1.0 https://github.com/Steaf23/BingoReloaded/releases/tag/v2.1.0
