### ISSUE TITLE
TP randomisation bias?

### ISSUE THREAD

**Issue by Vedvod** [Steaf23/BingoReloaded#11]
When using this plugin with three other players, we have noticed that we are always teleported within the pos x pos z quadrant of the world, though it is unclear if this is a bug or simply coincidence.

**Comment by Steaf23** [comment]
Hey, thanks for trying out my plugin. I have looked at it and can confirm that this is a bug. I will put it on my todo list, thanks for reporting!

**Comment by Steaf23** [comment]
fixed in 2.0.0
