### ISSUE TITLE
Potion effects wear off

### ISSUE THREAD

**Issue by chrisjanusa** [Steaf23/BingoReloaded#12]
Potion Effects are currently set to last 100,000 ticks (as set [here](https://github.com/Steaf23/BingoReloaded/blob/94179876adb5f14b249b332d946214a9bb1f4b77/BingoReloaded/src/main/java/io/github/steaf23/bingoreloaded/player/BingoPlayer.java#L154)) which is ~83 minutes but if a game goes over that they wear off. It would be better to set them to infinite using the [infinite duration constant ](https://hub.spigotmc.org/javadocs/spigot/constant-values.html#org.bukkit.potion.PotionEffect.INFINITE_DURATION).

**Comment by Steaf23** [comment]
Hey, thanks for playing my plugin. This seems like a small change however this constant was only added since 19.4 from what I can tell. I will use Integer.MAX_VALUE which should be big enough imo. Once I fully upgrade to version at and past 1.19.4 ill fix it properly
