### ISSUE TITLE
Disable durability when using the Overpowered or Reloaded Kits

### ISSUE THREAD

**Issue by chrisjanusa** [Steaf23/BingoReloaded#14]
It would be great if you didn't have to worry at all about armor or tools breaking when using the overpowered and above kits or maybe just add it as a config option. Here is [an example](https://github.com/Kustled/NoDurability/blob/main/src/main/java/me/kustled/nodurability/Nodurability.java) of how that could be done.

**Comment by Steaf23** [comment]
thanks for your suggestion, I will see whats possible in the near future
