### ISSUE TITLE
Mistitled config option of bingoWorldName vs defaultWorldName

### ISSUE THREAD

**Issue by chrisjanusa** [Steaf23/BingoReloaded#17]
I believe it was intended to have these match but they are different between the [ConfigData.java](https://github.com/Steaf23/BingoReloaded/blob/2fe91272b653f11b1d0aa820215d6550dfaeddd0/BingoReloaded/src/main/java/io/github/steaf23/bingoreloaded/data/ConfigData.java#L117) file and the [config.yml](https://github.com/Steaf23/BingoReloaded/blob/2fe91272b653f11b1d0aa820215d6550dfaeddd0/BingoReloaded/src/main/resources/config.yml#L13) file

**Comment by Steaf23** [comment]
Yes this is correct, if you want you can change it to be defaultWorldName in the config, else I will do it later
