### ISSUE TITLE
Bingo scoreboard timer persists after game end

### ISSUE THREAD

**Issue by scarlettcloud** [Steaf23/BingoReloaded#2]
### **Overview**
Once the scoreboard appears for a bingo game, the time stays on the screen, stopped, after the game ends. 

### **Tested on:**
1.19.2 Purpur (Spigot), hooked into Velocity network

### **Steps to Recretate:**
1. Open BR admin menu, select any game type or card
2. Start the game to see the timer scoreboard, and then end the game
3. Identify if scoreboard persists

**Relevant Logs**
N/A - no errors thrown

**Comment by Steaf23** [comment]
fixed in v1.3.0
