### ISSUE TITLE
License

### ISSUE THREAD

**Issue by FireInstall** [Steaf23/BingoReloaded#28]
May I ask you to add a license to your repo?
I'm a fan of your work but want to change some things around for our server and would like to know what is permitted with your code and what isn't.
You know, while we don't want to sell the plugin and properly never upload a .jar publically, it would be a relief knowing you are ok with me changing your code and distributing these changes over GitHub.

**Comment by Steaf23** [comment]
Thats a good idea, I will start looking into that soon. For now im fine with you making forks and whatever and change code as you see fit, just be sure to credit me somewhere I guess

**Comment by FireInstall** [comment]
sure thing!

**Comment by Steaf23** [comment]
added the GNU pgl 3 license since f37691b, since that is what Spigot also uses

**Comment by FireInstall** [comment]
thanks!
