### ISSUE TITLE
Bingo armor and inventories persist after game ends

### ISSUE THREAD

**Issue by scarlettcloud** [Steaf23/BingoReloaded#3]
### **Overview**
Items gathered during Bingo game, the bingo card, and armor applied through the bingo game admin menu, remain in the player's inventory and armor slots after the game ends

### **Tested on:**
1.19.2 Purpur (Spigot), hooked into Velocity network

### **Steps to Recretate:**
1. Open BR admin menu, select any game type or card, select a game mode other than Hardcore
2. Start the game to give players armor, then end the game
3. Players keep armor and inventory

### **Relevant Logs**
N/A - no errors thrown

**Comment by Steaf23** [comment]
Will be fixed in a big update

**Comment by scarlettcloud** [comment]
Closing as WIP with next release! Thanks!
