### ISSUE TITLE
Filter option breaks screen interactions

### ISSUE THREAD

**Issue by TheMegax** [Steaf23/BingoReloaded#32]
Running a Paper server on 1.20.2
Only using this plugin, Geyser and Floodgate.

**Comment by TheMegax** [comment]
Hello! Sorry I didn't explain. Clicking on the filter crashes the screen handler, and allows you to take items out of the inventory (eg. team color's helmets). Reopening the screen fixes it.

**Comment by TheMegax** [comment]
I compiled the project and yeah, AnvilGUI was outdated. Changing version from 1.7.0-SNAPSHOT to 1.9.0-SNAPSHOT fixes everything

**Comment by Steaf23** [comment]
Thanks for looking into it, will be fixed in the next update for everyone else :P

**Comment by Steaf23** [comment]
Fixed as of v2.0.2
