### ISSUE TITLE
Advancement Tasks no longer work on 1.20.2

### ISSUE THREAD

**Issue by chrisjanusa** [Steaf23/BingoReloaded#33]
Advancement tasks no longer work on 1.20.2 for some reason. I was able to fix this on my own branch by just changing [line 303 of BingoCard](https://github.com/Steaf23/BingoReloaded/blob/f51c185bb06e4a4f18334366ea70c20e4372ef39/BingoReloaded/src/main/java/io/github/steaf23/bingoreloaded/cards/BingoCard.java#L303) from
`if (data.advancement().equals(event.getAdvancement())) {`
to
`if (data.advancement().getKey().equals(event.getAdvancement().getKey())) {`

Not sure why this all of a sudden broke in 1.20.2 nor have I tested this on lower versions

**Comment by Steaf23** [comment]
I have gotten compaints from users about this too, thanks for finding the issue. Spigot probably messed something up with the recent updates breaking comparisons of advancement objects, using the key seems like a good solution. I will make a patch release later today

**Comment by Steaf23** [comment]
Fixed in Version 2.0.1 (see https://github.com/Steaf23/BingoReloaded/releases/tag/v2.0.1)
