### ISSUE TITLE
[Feature Request] Like other Minigames plugins, it can be automated to run

### ISSUE THREAD

**Issue by qaz197418i** [Steaf23/BingoReloaded#34]
Like other small game plugins, implement a system that can run automatically
1. Implement a waiting hall before the game starts
2. Implement automatic average team allocation based on the number of players joining the game
3. Realize that when there is only one team left in the server, it will be judged as winning and the game will automatically end (there must be at least two teams on the field for the game to proceed normally)
4. Implement automatic end of game after all players leave the server
5. Implement the function of prohibiting other players from joining midway during the game process

**Comment by Steaf23** [comment]
This feature is implemented as of V2.1.0 https://github.com/Steaf23/BingoReloaded/releases/tag/v2.1.0
