### ISSUE TITLE
[Feature Request] Translation improvement

### ISSUE THREAD

**Issue by qaz197418i** [Steaf23/BingoReloaded#35]
![image](https://github.com/Steaf23/BingoReloaded/assets/30312760/6a89c1e2-4d7e-444f-8c62-bd3554d24fd1)
![image](https://github.com/Steaf23/BingoReloaded/assets/30312760/87674f1b-0874-4e2d-a7e0-dd46ec2b5d8e)
Make these messages customizable for translation

**Comment by Steaf23** [comment]
This feature is implemented as of V2.1.0 https://github.com/Steaf23/BingoReloaded/releases/tag/v2.1.0
