### ISSUE TITLE
[Feature Request] Make the scoreboard of plugins more customizable

### ISSUE THREAD

**Issue by qaz197418i** [Steaf23/BingoReloaded#36]
![image](https://github.com/Steaf23/BingoReloaded/assets/30312760/c7bb61ac-30b3-4df3-a72f-8b48a62a1c24)
Make the scoreboard more customizable like other minigames plugins

**Comment by Steaf23** [comment]
This feature is implemented as of V2.1.0 https://github.com/Steaf23/BingoReloaded/releases/tag/v2.1.0
