### ISSUE TITLE
[Feature Request] Add PlaceholderAPI placeholder support

### ISSUE THREAD

**Issue by qaz197418i** [Steaf23/BingoReloaded#37]
Add support for PlaceholderAPI to display player information within the game
such as
player's team
team color
number of tasks completed by the player's team
game duration, etc

And it can support player data statistics
such as
how many bingo games they have played cumulatively
Their number of wins, etc

**Comment by Steaf23** [comment]
This feature is implemented as of V2.1.0 https://github.com/Steaf23/BingoReloaded/releases/tag/v2.1.0
