### ISSUE TITLE
FEATURE REQUESTS: Quality of life/player ease improvements to game design

### ISSUE THREAD

**Issue by scarlettcloud** [Steaf23/BingoReloaded#4]
**### Proposed Features:**

**1. Restore pre-game inventory on game end**
Some minigames plugins like RandomEvents save player inventories before game start, and restore them on game end. This would be helpful for anyone looking to run BingoReloaded on prod multiplayer survival servers, so that players do not have to manually remove and store their inventories before joining the game. Additionally would prevent players from using and keeping items found during Bingo to use in their survival play.

**2. Teleport players back to their original location on game end**
Another common feature of minigames plugins, could be implemented in a few ways by either asking the admin to set a warp location for a specific Bingo lobby that players are sent back to after game end, or storing their location when they join the game and sending them back when the game ends. 

**3. Mark card items as completed upon entering player inventories**
The other Bingo mods/plugins that I've played mark the items as completed when the item enters the player's inventory. I honestly don't know if this one is as important because I kind of like that players can't use items gathered for Bingo to then craft or create other items in Bingo, so perhaps the item still disappears on inventory enter. 

**4. Remove starting platforms automatically before damage immunity expires** 
This one is a nice to have. It would be cool if the glass platforms disappeared automatically before the damage immunity timer ran out. I haven't saved coords of start locations to test yet, but it would be good regardless to remove them after a set time if you haven't already incorporated that, just so the world isn't populated with little glass platforms 😄 

**5. Timed co-op or solo play**
This one is also a nice to have. Let players join the same team in a collaborative game, or let players play alone 😿 , potentially giving a set amount of time for completion before game end.

**Comment by Steaf23** [comment]
Thanks for making this issue, it really helps me to see what features I can add to make bingo more interesting!

1, 2, 3: I have a few big updates planned for this plugin, one of them being that the plugin can create worlds for a game of bingo and then destroy it once it's done. This means a lot of your suggestions would be adhered to automatically.

4: along with platforms being removed after the game (if the world is gonna get deleted) it makes sense to have the starting platform disappear after a short time (like 25 seconds). I will probably fit this into one of the future updates.

5: sounds like a fun addition, I will probably fit this into a future update, but the one thing holding be back is having a proper timer for countdowns, which I will repurpose for the start of the game once I finish that.

**Comment by Steaf23** [comment]
All of these features are now implemented in V2.1.0 https://github.com/Steaf23/BingoReloaded/releases/tag/v2.1.0
