### ISSUE TITLE
Lockout

### ISSUE THREAD

**Issue by Lym0s** [Steaf23/BingoReloaded#40]
I got a issue with lockout. Everytime one single goal has been completed from the lockout board the game ends. Thats not supposed to happen right? Lockout usually ends when the timer hits zero or one payer has completed more than half of the goals. Can anybody help me?

**Comment by Steaf23** [comment]
You are right, thats not supposed to happen. How many teams are you playing with and how many people are in each team? maybe we can narrow down the issue

**Comment by Lym0s** [comment]
Right now i am playing with a single team with only one player, myself. Ive wanted to set it up for a friend of mine and myself because we used the 1.19 lockout mod from smallant but wanted to upgrade to 1.20. Could me playing alone rly be the issue?

**Comment by Steaf23** [comment]
if you wanna play alone you could do compelet-all which is similar but doesnt have the lockout aspect, which wouldnt matter for singleplayer anyways
