### ISSUE TITLE
[1.21 Issue] Can't edit lists

### ISSUE THREAD

**Issue by Spikyp** [Steaf23/BingoReloaded#41]
Created a new world and installed the 1.21 plugin and imported the custom lists I created in the previous version. When trying to modify the currently available lists, none show up.

![Bingo list](https://github.com/Steaf23/BingoReloaded/assets/43733325/da28435e-7a51-497e-9c6f-78df6ea44cf9)

**Comment by Steaf23** [comment]
Did you get any console warnings or errors?

**Comment by Steaf23** [comment]
also can you show the lists file you ported over?

**Comment by Spikyp** [comment]
In the console I'm getting the following: ```
_[11:33:38 ERROR]: [playit-gg] Could not save config to plugins/playit-gg/config.yml
java.io.FileNotFoundException: plugins/playit-gg/config.yml (Permission denied)_
```

It has every persmission it could need [Read / Write]. Deleting the folder and setting it up from scratch shows the default lists but I can't seem to get it to work with my previous lists.

Here goes the 1.20 lists:

[_BingoReloaded_Issue.zip](https://github.com/user-attachments/files/15900153/_BingoReloaded_Issue.zip)

**Comment by Steaf23** [comment]
I dont know anything about playit.gg so that must be a different issue with that plugin. Did you rename the lists file to be lists_1_21.yml? 
this is important for bingo to see it in version 1.21. Also make sure to restart the plugin/server after you make changes to the yml files

**Comment by Spikyp** [comment]
Ah, thought the "lists_1.20" was just an arbitraty name given to the lists. Modifying the name solved the issue.

Thank you very much ❤️

**Comment by Steaf23** [comment]
Okay, glad its fixed :D
