### ISSUE TITLE
Feature Request: Bingo Check Difficulties

### ISSUE THREAD

**Issue by Pat4962** [Steaf23/BingoReloaded#48]
Would be very cool if in the future (this may take time as it would need you to reorganize every task) it would be possible to choose from one of three difficulties for the bingo checks. The easiest being basic stuff that just needs iron crafts, or leather, or some dyed wool/glass/concrete or whatnot. The hardest having some more difficult items like for example beacons or even just end stone or an end crystal or a wither skull and so on. The difficulty in between can have alot of variety

**Comment by Steaf23** [comment]
Thanks for using my plugin!

Using /bingo creator as an admin, you can create your own cards that can have any possible advancement, statistic or block on it that you want. So it is possible to make different cards at different difficulties, you can even make multiple lists of tasks for a single card or reuse lists for multiple cards. Finally you can configure each list in the card to use a certain number of items from it. This allows you create a card with 2 lists, where 1 list might have really hard items but only a few will be generated on the card. 

For this reason there is only 1 default card, as the server admin can create cards themselves however they want!

**Comment by Pat4962** [comment]
Oh i see what you mean so the cards could be random from any list, and list itself will pick a random item/check. Very cool i'll try it out. Maybe i'd add though to make it so that the default card doesn't have overlaps. Like for example one time i got 2 checks on the same card that were Obtain a bed and the Sweet Dreams advancement. To get sweet dreams you already need to get a bed so it kind of cancels it out. Maybe blacklist some specific checks from appearing on the same card? Nonetheless though very thankful i'll try to make a custom card hoping it wouldn't be too difficult
