### ISSUE TITLE
I noticed a few things about the game:

### ISSUE THREAD

**Issue by Leahcimkrob** [Steaf23/BingoReloaded#9]
I noticed a few things about the game:
- The commands at https://github.com/Steaf23/BingoReloaded/blob/main/AutoBingo.md do not work.
- You don't spawn in the world you were teleported from after the game.
- The map will be deleted if you right-click on it
- After the end of the game you have to leave the game first, it doesn't end automatically.

**Comment by Steaf23** [comment]
Hey, You are correct about the commands being wrong, as I have updated their description prematurely. A working version of the commands can be found [here](https://github.com/Steaf23/BingoReloaded/blob/1.5.0_fixes/AutoBingo.md). 

Right now the plugin  is not designed for use along side another world/ playthrough of the game, but just as a fun party minigame. I am in the middle of an update that will add features to do this however. 

As for the other bugs you've mentioned, i will have to look into them as they seem like genuine bugs

**Comment by Steaf23** [comment]
These issues have not been seen in V2.1.0 https://github.com/Steaf23/BingoReloaded/releases/tag/v2.1.0, closing for now
